### ISSUE TITLE
Looks like matplotlib may be broken in our current builds

### ISSUE THREAD

**Issue by jmikeowen** [LLNL/spheral#171]
When I try to import modules from matplotlib into the current Spack based Spheral I see unresolved errors related to the PNG library:

>>> from Spheral3d import *
/------------------------------------------------------------------------------\
|  Spheral version             : HEAD 3508b54d1 8596                           |
|  LLNLSpheral version         : develop 7b1fdb1 971                           |
|    number of MPI tasks       : 1                                             |
|    number of threads per rank: 36                                            |
\------------------------------------------------------------------------------/
Spheral> from stl import mesh
Spheral> from mpl_toolkits import mplot3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/mpl_toolkits/mplot3d/__init__.py", line 6, in <module>
    from .axes3d import Axes3D
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 24, in <module>
    import matplotlib.axes as maxes
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/matplotlib/axes/__init__.py", line 4, in <module>
    from ._subplots import *
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 10, in <module>
    from matplotlib.axes._axes import Axes
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 22, in <module>
    import matplotlib.contour as mcontour
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/matplotlib/contour.py", line 23, in <module>
    import matplotlib.text as text
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/matplotlib/text.py", line 22, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/matplotlib/textpath.py", line 20, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/usr/gapps/Spheral/toss_3_x86_64_ib/spheral-971-8596/.venv/lib/python2.7/site-packages/matplotlib/mathtext.py", line 38, in <module>
    from matplotlib import _png, colors as mcolors, get_data_path, rcParams
ImportError: libpng16.so.16: cannot open shared object file: No such file or directory

**Comment by mdavis36** [comment]
Closing due to the python3 port.
