### ISSUE TITLE
errors occurred while executing the install command

### ISSUE THREAD

**Issue by duxingderen** [LLNL/spheral#61]
[  3%] Performing build step for 'python'
CMake Error at pybind11/pybind11/tmp/pybind11-download-Release.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-P' '/usr/Spheral_release/BUILD/pybind11/pybind11/tmp/pybind11-download-impl.cmake'

  See also

    /usr/Spheral_release/BUILD/pybind11/pybind11/src/pybind11-stamp/pybind11-download-*.log

CMake Error at eigen/tmp/eigen-download-Release.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-P' '/usr/Spheral_release/BUILD/eigen/tmp/eigen-download-impl.cmake'

  See also

    /usr/Spheral_release/BUILD/eigen/src/eigen-stamp/eigen-download-*.log

CMake Error at opensubdiv/tmp/opensubdiv-download-Release.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-P' '/usr/Spheral_release/BUILD/opensubdiv/tmp/opensubdiv-download-impl.cmake'

  See also

    /usr/Spheral_release/BUILD/opensubdiv/src/opensubdiv-stamp/opensubdiv-download-*.log

CMake Error at aneos/tmp/aneos-download-Release.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-P' '/usr/Spheral_release/BUILD/aneos/tmp/aneos-download-impl.cmake'

  See also

    /usr/Spheral_release/BUILD/aneos/src/aneos-stamp/aneos-download-*.log

CMake Error at qhull/tmp/qhull-download-Release.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-P' '/usr/Spheral_release/BUILD/qhull/tmp/qhull-download-impl.cmake'

  See also

    /usr/Spheral_release/BUILD/qhull/src/qhull-stamp/qhull-download-*.log

make[2]: *** [CMakeFiles/pybind11.dir/build.make:98: pybind11/pybind11/src/pybind11-stamp/pybind11-download] Error 1
make[2]: *** [CMakeFiles/opensubdiv.dir/build.make:98: opensubdiv/src/opensubdiv-stamp/opensubdiv-download] Error 1
make[2]: *** [CMakeFiles/eigen.dir/build.make:98: eigen/src/eigen-stamp/eigen-download] Error 1
make[2]: *** [CMakeFiles/aneos.dir/build.make:98: aneos/src/aneos-stamp/aneos-download] Error 1
make[2]: *** [CMakeFiles/qhull.dir/build.make:98: qhull/src/qhull-stamp/qhull-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:1886: CMakeFiles/pybind11.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1808: CMakeFiles/aneos.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2206: CMakeFiles/eigen.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2396: CMakeFiles/opensubdiv.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2448: CMakeFiles/qhull.dir/all] Error 2

**Comment by jmikeowen** [comment]
Have you looked at those download log files the make system is indicating?  It looks like all the third party libraries are not downloading, so likely something common is wrong like wget is not installed.

**Comment by duxingderen** [comment]
THANK YOU !!

However, while executing the cmake command, the following errors occurs. How to resolve it? Do you have any good ideas? In addition, do the following errors in cmake directly cause the failure of downloading third-party libraries when executing the make command?


CMakeError.log :
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/Spheral_release/BUILD/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_f9ddf/fast && /usr/bin/make  -f CMakeFiles/cmTC_f9ddf.dir/build.make CMakeFiles/cmTC_f9ddf.dir/build
make[1]: Entering directory '/home/Spheral_release/BUILD/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f9ddf.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD  -Wall -Wextra   -fPIE -o CMakeFiles/cmTC_f9ddf.dir/src.c.o -c /home/Spheral_release/BUILD/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_f9ddf
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f9ddf.dir/link.txt --verbose=1
/usr/bin/cc   -Wall -Wextra   -rdynamic CMakeFiles/cmTC_f9ddf.dir/src.c.o -o cmTC_f9ddf
/usr/bin/ld: CMakeFiles/cmTC_f9ddf.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x5e): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x6f): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_f9ddf.dir/build.make:99: cmTC_f9ddf] Error 1
make[1]: Leaving directory '/home/Spheral_release/BUILD/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_f9ddf/fast] Error 2


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/Spheral_release/BUILD/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_b1197/fast && /usr/bin/make  -f CMakeFiles/cmTC_b1197.dir/build.make CMakeFiles/cmTC_b1197.dir/build
make[1]: Entering directory '/home/Spheral_release/BUILD/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b1197.dir/CheckFunctionExists.c.o
/usr/bin/cc   -Wall -Wextra  -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE -o CMakeFiles/cmTC_b1197.dir/CheckFunctionExists.c.o -c /usr/share/cmake-3.20/Modules/CheckFunctionExists.c
Linking C executable cmTC_b1197
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b1197.dir/link.txt --verbose=1
/usr/bin/cc   -Wall -Wextra  -DCHECK_FUNCTION_EXISTS=pthread_create -rdynamic CMakeFiles/cmTC_b1197.dir/CheckFunctionExists.c.o -o cmTC_b1197  -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_b1197.dir/build.make:99: cmTC_b1197] Error 1
make[1]: Leaving directory '/home/Spheral_release/BUILD/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_b1197/fast] Error 2

**Comment by duxingderen** [comment]
In addition, you told me to use wget to download the third-party libraries. I tried after cmake, but found that there would be another error in the make command. how to resolve it?


[  2%] Performing configure step for 'pybind11'
[  2%] Generating qhull/src/qhull-stamp/qhull-update
[  2%] Performing configure step for 'zlib'
[  2%] Performing patch step (custom command) for 'qhull'
patch: '&&': extra operand
patch: Try 'patch --help' for more information.
CMake Error at /usr/share/cmake-3.20/Modules/ExternalProject/captured_process_setup.cmake:29 (message):
Call Stack (most recent call first):
  /usr/share/cmake-3.20/Modules/ExternalProject/captured_process_setup.cmake:53 (_ep_message_quiet_capture)
  qhull/tmp/qhull-patch.cmake:16 (_ep_command_check_result)


make[2]: *** [CMakeFiles/qhull.dir/build.make:113: qhull/src/qhull-stamp/qhull-patch] Error 1
make[1]: *** [CMakeFiles/Makefile2:2448: CMakeFiles/qhull.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- eigen download command succeeded.  See also /home/Spheral_release/BUILD/eigen/src/eigen-stamp/eigen-download-*.log
[  2%] Generating eigen/src/eigen-stamp/eigen-update
[  2%] Skipping patch step (no custom command) for 'eigen'

**Comment by duxingderen** [comment]
@jmikeowen

**Comment by mdavis36** [comment]
For the pthread related error, it seems as though your compiler is failing to link properly to the pthread lib. What compiler are you using? We recommend at least `gcc-8`. As for the patch command error, that does look unusual. Try to reinstall / updating `patch` and perhaps your system if it has been a while. If you don't already, it would be useful to make sure you have some basic development kits. If you are on Ubuntu try installing `build-essentials` (or your distros equivalent). 

Once that is done I would recommend completely wiping away this build directory and starting from fresh, sometimes failed tpl build/installs can be finicky when trying to pick them back up and continue where you left off.

**Comment by mdavis36** [comment]
Closing due to inactivity, @duxingderen we can open this up again if you have further issues.

**Comment by duxingderen** [comment]
@mdavis36 ok, thanks! @jmikeowen @mdavis36 Excuse me. However, a new problem has arisen. So, what could I do to solve it?

[  5%] Generating tpl/cache/.pip-modules_pip_download.stamp
-- pip downloading pip-modules
Exception:
Traceback (most recent call last):
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/commands/download.py", line 198, in run
    requirement_set.prepare_files(finder)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 37, in send
    cached_response = self.controller.cached_request(request)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 111, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 114, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 176, in _loads_v2
    cached = json.loads(zlib.decompress(data).decode("utf8"))
error: Error -5 while decompressing data: incomplete or truncated stream
make[2]: *** [CMakeFiles/pip-modules.dir/build.make:76：tpl/cache/.pip-modules_pip_download.stamp] 错误 2
make[1]: *** [CMakeFiles/Makefile2:1827：CMakeFiles/pip-modules.dir/all] 错误 2
make: *** [Makefile:146：all] 错误 2
