### ISSUE TITLE
errors occurred while executing the install command

### ISSUE THREAD

**Issue by duxingderen** [LLNL/spheral#70]
Excuse me. However, a new problem has arisen. So, how to solve it? Thanks! 

[ 5%] Generating tpl/cache/.pip-modules_pip_download.stamp
-- pip downloading pip-modules
Exception:
Traceback (most recent call last):
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/commands/download.py", line 198, in run
requirement_set.prepare_files(finder)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
session=self.session, hashes=hashes)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
hashes=hashes
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
hashes)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
stream=True,
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
return self.request('GET', url, **kwargs)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/download.py", line 386, in request
return super(PipSession, self).request(method, url, *args, **kwargs)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
resp = self.send(prep, **send_kwargs)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
r = adapter.send(request, **kwargs)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 37, in send
cached_response = self.controller.cached_request(request)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 111, in cached_request
resp = self.serializer.loads(request, cache_data)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 114, in loads
return getattr(self, "_loads_v{0}".format(ver))(request, data)
File "/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 176, in _loads_v2
cached = json.loads(zlib.decompress(data).decode("utf8"))
error: Error -5 while decompressing data: incomplete or truncated stream
make[2]: *** [CMakeFiles/pip-modules.dir/build.make:76：tpl/cache/.pip-modules_pip_download.stamp] error 2
make[1]: *** [CMakeFiles/Makefile2:1827：CMakeFiles/pip-modules.dir/all] error 2
make: *** [Makefile:146：all] error 2

**Comment by lrtfm** [comment]
Maybe your network connection results in this.

**Comment by jmikeowen** [comment]
That looks like a third party library download failed.  You should try a fresh build (from scratch) with a reliable network and see how it goes.

**Comment by duxingderen** [comment]
@lrtfm That's true. Thanks!

**Comment by duxingderen** [comment]
@jmikeowen Ok, thank you! The  software package really need a reliable network. After that, I tried a few more times, it was better. However, at [100%], there was an error again, but it seemed to have nothing to do with the network. How to set this permission? Thanks! 


[100%] Generating SpheralHelmholtz.cc
[100%] Building CXX object src/Pybind11Wraps/Helmholtz/CMakeFiles/SpheralHelmholtz.dir/SpheralHelmholtz.cc.o
[100%] Linking CXX shared library ../../../lib/SpheralHelmholtz.so
/usr/bin/ld: missing --end-group; added as last command line option
[100%] Built target SpheralHelmholtz
[100%] Building HTML documentation with Sphinx
/home/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/sphinx/util/nodes.py:94: FutureWarning: 
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  for classifier in reversed(node.parent.traverse(nodes.classifier)):
/home/Spheral/docs/index.rst:6: WARNING: duplicate label welcome to spheral's documentation!, other instance in /home/Spheral/docs/contents.rst
/home/Spheral/docs/index.rst:16: WARNING: duplicate label indices and tables, other instance in /home/Spheral/docs/contents.rst
/home/Spheral/docs/contents.rst: WARNING: document isn't included in any toctree
[100%] Built target Spheral_docs
Built target pybind11
Built target boost
Built target hdf5
Built target aneos
Built target zlib
Consolidate compiler generated dependencies of target gtest
CMake Error: Cannot open file for write: /home/Spheral_release/BUILD/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeFiles/gtest.dir/compiler_depend.make.tmpedb2d
CMake Error: : System Error: Permission denied
make[2]: *** [blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeFiles/gtest.dir/build.make:109: blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeFiles/gtest.dir/depend] Error 2
make[1]: *** [CMakeFiles/Makefile2:3273: blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeFiles/gtest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Built target eigen
Built target qhull
Built target opensubdiv
Built target fruit
make: *** [Makefile:146: all] Error 2

**Comment by duxingderen** [comment]
I have tried to set this permission with   $sudo chmod -R 777 home,  but it didn't seem to work. So, have any ideas?

**Comment by duxingderen** [comment]
I have tried to set this permission with $sudo chmod -R 777 home, but it didn't seem to work. So, have any ideas?
