### ISSUE TITLE
Errors in creating Spheral virtual python environment: PolyClipper.so not found!

### ISSUE THREAD

**Issue by lrtfm** [LLNL/spheral#72]
Everything goes well when I run `make`, except the last step in creating Spheral virtual python environment.

I searched the `Spheral_release` directory and did not found the `so` file elsewhere.

Could someone point out why this happened, or tell me how to find the reason?

```
Creating Spheral virtual python environment ...
created virtual environment CPython2.7.18.final.0-64 in 3333ms
  creator CPython2Posix(dest=/home/liuchang/soft/Spheral_release/.venv, clear=False, no_vcs_ignore=False, global=True)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/liuchang/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==44.1.1, wheel==0.36.1
  activators PythonActivator,CShellActivator,FishActivator,PowerShellActivator,BashActivator
Installing Spheral ...
cp: cannot stat ‘/home/liuchang/soft/Spheral_release/tpl/polyclipper/511684c4b491a06d2b0eac53cc11fd02/PolyClipper.so’: No such file or directory
Installing Gnuplot, ats ...
cp: cannot stat ‘/home/liuchang/soft/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/Gnuplot’: No such file or directory
cp: cannot stat ‘/home/liuchang/soft/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/ats’: No such file or directory
Creating spheral symlink to spheral-env script ...
```

[make-install.log](https://github.com/LLNL/spheral/files/6705901/build.log)

**Comment by jmikeowen** [comment]
It looks like there's some outdated install instructions for those packages in the Spheral build system (needs to be fixed).  However, it also looks like Spheral built OK and should be working despite those out of date install recipes.  Have you tried running the "spheral" executable and seen if it's working?

**Comment by lrtfm** [comment]
I just run `spheral -c "import Spheral"`. It seems ok. I haven't tested other things.

```bash
[liuchang@mu01 BUILD]$ ../spheral -c "import Spheral"
/------------------------------------------------------------------------------\
|  Spheral version             : develop db6d892 6868                          |
|    number of MPI tasks       : 1                                             |
|    number of threads per rank: 12                                            |
\------------------------------------------------------------------------------/
```

**Comment by jmikeowen** [comment]
Yep, that looks OK.  You should be good to go.

**Comment by lrtfm** [comment]
Thanks！

**Comment by lrtfm** [comment]
When I run the test file:
```
Spheral_release/spheral Sod-planar-1d.py
```
the following error shows:
```
Energy conservation: original=0.884678, final=0.884678, error=-1.63143e-15
Traceback (most recent call last):
  File "Sod-planar-1d.py", line 621, in <module>
    from SpheralGnuPlotUtilities import multiSort
  File "/home/liuchang/soft/Spheral_release/.venv/lib/python2.7/site-packages/Spheral/SpheralGnuPlotUtilities.py", line 1, in <module>
    import Gnuplot
```

It seems that the `Gnuplot` is missing.

**Comment by mdavis36** [comment]
@lrtfm Please see PR #75 for a fix to this issue

**Comment by lrtfm** [comment]
@mdavis36 Thanks. By the way, where can I find the manual of `Spheral`? Only installation information is available at https://spheral.readthedocs.io/en/latest/.

**Comment by mdavis36** [comment]
@lrtfm readthedocs is the most up to date documentation on building and installing Spheral. A full documentation / manual is currently a work in progress.
